### PR TITLE
Plone 5 compat

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
the travis setup needs some love

**Comment by jensens** [comment]
i think this is has some todos open:

- [ ] README update (see #23 )
- [ ] Semantic Versioning: Bump to 3.0 because we're not BBB
- [ ] use lessvars, at least for bgcolor.

**Comment by davilima6** [comment]
@jensens I think this is good for at least merging with master (if not for a release). What do you think?

**Comment by jensens** [comment]
@davilima6 yes, merging is needed!

**Comment by thet** [comment]
possibly there are upgrade steps missing? all configuration is now stored in plone.app.registry.

**Comment by thet** [comment]
Before merging we need a upgrade step from portal properties based configuration to plone.app.registry ones. E.g. ``enable_thumbs`` was changed to ``enable_images``.

An upgrade step or good arguments, why we don't need that...

**Pull request merged**
